server:
  port: 8081

spring:
  application:
    name: condominium-management-api

  datasource:
    url: jdbc:h2:mem:condominiumdb
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: true